# Do not insert a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$cmake\
$nodejs\
$php\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

#[character]
#success_symbol = "[➜](bold green) "
#error_symbol = "[➜](bold red) "

# Disable 2 line prompt
[line_break]
disabled = true

# Disable git (because I dont want it to show git :))
[git_state]
disabled = true
